sonar.projectKey=mattewwung_MYRN
sonar.organization=mattewwung

sonar.sources=.
sonar.exclusions=node_modules/**, android/**, ios/**, coverage/**, .bundle/**, vendor/**, **/*.config.js, **/*.setup.js, **/assets/**

sonar.tests=.
sonar.test.inclusions=**/__tests__/**/*.{js,jsx,ts,tsx}, **/*.test.{js,jsx,ts,tsx}

sonar.javascript.lcov.reportPaths=./coverage/lcov.info