# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    setup_ci if is_ci

	  # match 会自动在本地/CI 安装描述文件
	  match(type: "appstore", readonly: is_ci)
    increment_build_number(xcodeproj: "MYRN.xcodeproj")
    build_app(
      workspace: "MYRN.xcworkspace", 
      scheme: "MYRN",
      export_method: "app-store",
      clean: true
    )
    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )
  end
end
